name: first-workflow

on:
  push:

jobs:
  learn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Can Python import app?
        working-directory: backend
        run: |
          python -c "import app; print(app.__file__)"
      - name: Debug environment
        working-directory: backend
        run: |
          pwd
          ls -la
          python --version
          python -c "import sys; print(sys.path)"
          python -c "import os; print(os.getcwd())"
      - name: Run tests
        working-directory: backend
        run: pytest
