name: first-workflow

on:
  push:

jobs:
  learn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Show pytest version
        working-directory: backend
        run: |
          which pytest
          pytest --version
          python -m pytest --version
      - name: Run test
        working-directory: backend
        run: python -m pytest -v
