name: first-workflow

on:
  push:

jobs:
  learn:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: db
          POSTGRES_USER: root
          POSTGRES_PASSWORD: toor
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test
        working-directory: backend
        env:
          DB_HOST: localhost
          DB_NAME: db
          DB_USER: root
          DB_PASSWORD: toor
        run: python -m pytest -v

      - name: Check Docker
        run: docker --version

      - name: Docker Build
        working-directory: backend
        run: docker build -t myapp:test .

      - name: Show Images
        run: docker images

      - name: Run Docker image
        run: |
          docker run -d \
          --name flask-test \
          -p 5000:5000 \
          myapp:test

      - name: Test Container
        run: |
          sleep 5
          curl http://127.0.0.1:5000

      - name: Stop Container
        if: always()
        run: docker stop flask-test && docker rm flask-test
